/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.5-dev at Wed Oct 21 18:57:35 2015. */

#ifndef PB_PLATE_SAMPLER_PB_H_INCLUDED
#define PB_PLATE_SAMPLER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
