/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.5-dev at Wed Oct 21 18:57:35 2015. */

#include "plate_sampler.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif




