




.build_ano/uno/src/sampler.cpp : src/sampler.ino
	@mkdir -p .build_ano/uno/src
	@echo [93msrc/sampler.ino[0m
	@/home/liam/.local/bin/ano preproc --source-dir src  -o $@ $^


all : .build_ano/uno/src/sampler.cpp
	@true

